routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::get('users/{user}/profile', 'UserController@profile')->name('users.profile');
    Route::resource('users', 'UserController');
    Route::resource('posts', 'PostController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::put('roles/{role}/permissions', 'RoleController@updatePermissions')->name('roles.permissions.update');
    Route::get('permissions/{permission}/roles', 'PermissionController@getRoles')->name('permissions.roles.view');
    Route::post('permissions/{permission}/roles', 'PermissionController@updateRoles')->name('permissions.roles.update');
});

app/Permission.php
<?php

namespace App;

class Permission extends \Spatie\Permission\Models\Permission
{
    //
}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class PermissionController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();
        $permissions = Permission::all();
        return view('permissions.index', compact('permissions', 'roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::get();
        return view('permissions.create')->with('roles', $roles);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, ['name' => 'required|max:40|unique:permissions']);

        if ($permission = Permission::create($request->only('name'))) {

            if ($request->has('roles')) {
                $roles = Role::find($request->get('roles', []));
                foreach ($roles as $role) {
                    $role->givePermissionTo($permission);
                }
            }

            flash('Permission: ' . $request->name . ' added');
        } else {
            flash('Unknown Permission');
        }

        if ($request->ajax()) {
            return response()->json(['message' => 'Permission: ' . $request->name . ' added']);
        }

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect('permissions');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permission = Permission::find($id);

        return view('permissions.edit', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, ['name' => 'required|max:40']);

        if ($perm = Permission::find($id)) {

            $perms = Permission::get()->where('name', $request->name)->pluck('name');

            if ($request->name != $perm->name && in_array($request->name, $perms->toArray())) {
                return response()->json(['name' => ['Permission: \'' . $request->name . '\' is already in-use']], 422);
            } else {
                // update permission name
                $perm->fill($request->except('roles'))->save();

                // Revoke this permission from all existing roles...
                $roles = Role::get();
                foreach ($roles as $role) {
                    $role->revokePermissionTo($perm);
                }

                // Re-assign permission to only selected roles...
                $roles = Role::find($request->get('roles', []));
                foreach ($roles as $role) {
                    $role->givePermissionTo($perm);
                }

                flash('Permission: ' . $perm->name . ' updated!');
            }

        } else {
            flash()->error('Unknown permission.');
        }

        if ($request->ajax()) {
            return response()->json(['message' => 'Permission: ' . $request->name . ' added']);
        }

        return redirect()->route('permissions.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $permission = Permission::findOrFail($id);

        $permission->delete();

        flash('Permission has been dropped!');

        if ($request->ajax()) {
            return response()->json(['message' => 'Permission has been dropped']);
        }

        return redirect()->route('permissions.index');
    }

    /**
     * Get roles having this permission
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function getRoles(Request $request, $id)
    {

        if (!$permission = Permission::find($id)) {
            return response()->json(['error' => 'Unknown permission'], 201);
        }

        if ($request->ajax()) {
            return response()->json(['roles' => $permission->roles->pluck('id')]);
        }

        return response()->json(['roles' => $this->array_extract($permission->roles->toArray(), ['id', 'name'])]);
    }

    /**
     * Extract subset of array using keys
     * @param $array
     * @param $keys
     * @return array
     */
    private function array_extract($roles, $keys)
    {
        // Source: https://stackoverflow.com/a/569502
        $roles_subset = array();
        foreach ($roles as $role) {
            array_push($roles_subset, array_intersect_key($role, array_flip(['id', 'name'])));
        }
        return $roles_subset;
    }

}

resources/views/permissions/index.blade.php
@extends('layouts.app')

@section('title', '| Permissions')

@section('content')

    <div class="container">

        @include('flash::message')

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span><strong>Permissions</strong></span>
                        <span class="pull-right">
                            <a href="#" class="btn btn-success btn-sm" data-toggle="modal" data-target="#add-permission-modal">Add Permission</a>
                        </span>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped">

                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th class="hidden">ID</th>
                                    <th>Permission</th>
                                    <th>Roles</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>

                                <tbody>
                                @foreach ($permissions as $index => $perm)
                                    <tr>
                                        <td>{{ ++$index }}</td>
                                        <td data-bind="perm-id" class="hidden">{{ $perm->id }}</td>
                                        <td data-bind="perm-name">{{ $perm->name }}</td>
                                        <td data-bind="perm-roles">{{--[{{ $perm->roles->count() }}]--}} {{ $perm->roles->implode('name', ', ') }}</td>
                                        <td class="text-center">
                                            <a href="#" class="btn btn-info btn-xs" data-toggle="modal" data-target="#edit-permission-modal"
                                               style="margin-top: 2px;">
                                                <i class="glyphicon glyphicon-pencil"></i> Edit
                                            </a>
                                            <a href="#" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#drop-permission-modal"
                                               style="margin-top: 2px;">
                                                <i class="glyphicon glyphicon-trash"></i> Drop
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{-- Add Permission Modal --}}
    <div class="modal fade" id="add-permission-modal" tabindex="-1" role="dialog" aria-labelledby="addPermissionModalLabel">

        <div class="modal-dialog" role="document">

            <form id="add-permission" method="POST" action="{{ route('permissions.store') }}" role="form">

                <div class="modal-content">

                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="addPermissionModalLabel">Add Permission</h4>
                    </div>

                    <div class="modal-body">

                        {{ csrf_field() }}

                        <div class="form-group">
                            <label for="name" class="control-label">Name</label>
                            <input id="name" type="text" class="form-control" name="name" value="" required autofocus>
                        </div>

                        <div class="form-group">
                            <label for="name" class="control-label">Assign to...</label>
                            @foreach($roles as $role)
                                <div class="checkbox">
                                    <label class="">
                                        <input name="roles[]" type="checkbox" value="{{ $role->id }}"> {{ $role->name }}
                                    </label>
                                </div>
                            @endforeach
                        </div>

                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                        <input type="submit" class="btn btn-success btn-sm" value="Add">
                    </div>

                </div>

            </form>

        </div>

    </div>

    {{-- Edit Permission Modal --}}
    <div class="modal fade" id="edit-permission-modal" tabindex="-1" role="dialog" aria-labelledby="editPermissionModalLabel">

        <div class="modal-dialog" role="document">

            <form id="edit-permission" method="POST" action="{{ route('permissions.update', $perm->id) }}" role="form">

                <div class="modal-content">

                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="editPermissionModalLabel">Edit Permission</h4>
                    </div>

                    <div class="modal-body">

                        {{ csrf_field() }}

                        {{ method_field('PUT') }}

                        <input id="perm-id" type="hidden" name="id" value="">

                        <div class="form-group">
                            <label for="name" class="control-label">Name</label>
                            <input id="perm-name" type="text" class="form-control" name="name" value="" required autofocus>
                        </div>

                        <div class="form-group">
                            <label for="name" class="control-label">Belong to...</label>
                            @foreach($roles as $role)
                                <div class="checkbox">
                                    <label class="">
                                        <input id="perm-roles" name="roles[]" type="checkbox" value="{{ $role->id }}"> {{ $role->name }}
                                    </label>
                                </div>
                            @endforeach
                        </div>

                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                        <input type="submit" class="btn btn-success btn-sm" value="Update">
                    </div>

                </div>

            </form>

        </div>

    </div>

    {{-- Drop Permission Modal --}}
    <div class="modal fade" id="drop-permission-modal" tabindex="-1" role="dialog" aria-labelledby="dropPermissionModalLabel">

        <div class="modal-dialog" role="document">

            <form id="drop-permission" method="POST" action="{{ route('permissions.destroy', $perm->id) }}" data-role-id="" role="form">

                <div class="modal-content">

                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="addPermissionModalLabel">Drop Permission</h4>
                    </div>

                    <div class="modal-body">

                        <div class="alert alert-danger">
                            Are you sure you want to drop the <strong>'<span id="perm-name"></span>' </strong>permission?
                        </div>

                        {{ csrf_field() }}

                        {{ method_field('DELETE') }}

                        <input id="perm-id" type="hidden" name="id" value="">

                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                        <input type="submit" class="btn btn-danger btn-sm" value="Drop">
                    </div>

                </div>

            </form>

        </div>

    </div>

@endsection